### PR TITLE
update to nicehash API v2

### PR DESCRIPTION
**Pull request by kilves**
$apisecret and $organization found on lines 44 and 45.
Closes: #1

### CODE REVIEW

**Comment by cryptowhizzard** [comment]
Hi, sorry for my late response, i did not have this on my watch list :(

Have you tested this, because it looks like it is not working here. I will add some debugging when i have time soon.

**Comment by kilves** [comment]
Yeah, I didn't test it, but admittedly I should have. No problem, I'll set up my own test environment and check it out soon.

**Comment by cryptowhizzard** [comment]
any progress on this? i did some debugging for curl, it comes back 401 unauthorized when doing the hashrate / algo request.

**Comment by kilves** [comment]
I haven't managed to set up my test environment yet. I should have everything configured but when I try to load /index.php, there's only a blank page. My nginx configuration looks like this:

        root /home/kilves/Projects/yiimp/web;
        server_name _;
        error_page 404 /var/www/html/404.html;
        error_page 500 502 503 504 /var/www/html/50x.html;

        location / {
                try_files $uri @rewrite;
        }

        location @rewrite {
                rewrite ^/(.*)$ /index.php?r=$1;
        }

        location ~ \.php$ {
                include fastcgi.conf;
                fastcgi_pass unix:/run/php/php7.2-fpm.sock;
                fastcgi_index index.
        }

When I force all errors and warnings to be visible with xdebug, I get a `session_start(): A session had already been started - ignoring` error. But if I fix it by adding a check before `session_start()`, there's no errors, just a blank page and nothing in any logs either.

But I should probably just give up on this and test my functions separately from the app, it would be faster that way. I'll look into it in a few hours after work.

**Comment by cryptowhizzard** [comment]
Most errors you can find in the runtime directory ( Application.log ).

**Comment by kilves** [comment]
There, now it should be fixed. I also changed indentation back to tabs instead of spaces, since it seems to be the project's convention.

**Comment by kilves** [comment]
I'm just pinging you here in case you don't have notifications on bountysource. @cryptowhizzard could you approve my bounty claim on bountysource please? https://www.bountysource.com/issues/80728786-nicehash-api-v2

**Pull request merged**
